baseURL = "https://movegb.now.sh"
locale = "en-GB"
title = "MoveGB Scam"
description = "How Move GB is conning people with dark patterns."

# Syntax highlighting. Themes include solarized-dark, autumn,
# github, friendly, monokai, monokailight ashen

enableRobotsTXT = true

sectionPagesMenu = "section"

[security]
  allowContent = ['^text/html$', 'markdown']
  enableInlineShortcodes = true

[[ menu.main ]]
  name = "Move GB scam"
  pageRef = "/"
  weight = "10"

[[ menu.main]]
  name = "about"
  pageRef = "/about/"
  weight = "20"

[[ menu.main ]]
  name = "posts"
  pageRef = "/posts/"
  weight = "30"

[[ menu.main ]]
  name = "images"
  pageRef = "/posts/images/"
  weight = "35"
[[ menu.main ]]
  name = "links"
  pageRef = "/links/"
  weight = "40"

[markup]
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "ashen"
    tabWidth = 4

  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.parser.attribute]
    block = true
    title = true
    
[ params ]
  headline = "Dark patterns in the industry"
  subhead = "For the first time ever a courageous <span>Move GB</span> user speaks out and reveals the abominable goings on in that nefarious organisation."